# Generated by Django 5.0.1 on 2024-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='tags',
            field=models.JSONField(default=''),
        ),
    ]
