# Generated by Django 5.0.1 on 2024-01-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0002_searchentry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
