# Generated by Django 5.0.1 on 2024-01-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0003_alter_searchentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
