# Generated by Django 5.0.1 on 2024-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0004_alter_searchentry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='tags',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
