# Generated by Django 5.0.1 on 2024-01-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0012_alter_searchentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
