# Generated by Django 5.0.1 on 2024-01-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0026_alter_searchentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
