# Generated by Django 5.0.1 on 2024-01-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0027_alter_searchentry_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
