# Generated by Django 5.0.1 on 2024-01-31 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0029_alter_searchentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='tags_test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=[], size=None),
        ),
    ]
