# Generated by Django 5.0.1 on 2024-01-31 00:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0030_searchentry_tags_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='tags_test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default='list', size=None),
        ),
    ]
