# Generated by Django 5.0.1 on 2024-02-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchapp', '0031_alter_searchentry_tags_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchentry',
            name='tags',
        ),
    ]
