# Generated by Django 4.1.dev20220204191113 on 2023-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
