# Generated by Django 4.1.dev20220204191113 on 2023-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0002_alter_searchentry_link_alter_searchentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=None),
        ),
    ]
