# Generated by Django 4.1.dev20220204191113 on 2023-01-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0003_searchentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='static/'),
        ),
    ]
