# Generated by Django 4.1.dev20220204191113 on 2023-01-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0004_alter_searchentry_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchentry',
            name='file',
        ),
    ]
