# Generated by Django 4.1.dev20220204191113 on 2023-01-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0005_remove_searchentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='tag',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
