# Generated by Django 4.1.dev20220204191113 on 2023-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0006_searchentry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='tag',
            field=models.CharField(default='', max_length=600),
        ),
    ]
