# Generated by Django 4.1.dev20220204191113 on 2023-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0007_alter_searchentry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='tag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
