# Generated by Django 4.1.dev20220204191113 on 2023-01-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0008_alter_searchentry_description_alter_searchentry_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
