# Generated by Django 4.1.dev20220204191113 on 2023-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0009_searchentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='file',
            field=models.FileField(upload_to='static'),
        ),
    ]
