# Generated by Django 4.1.dev20220204191113 on 2023-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0011_remove_searchentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='file',
            field=models.FileField(default='', upload_to='static'),
        ),
    ]
