# Generated by Django 4.1.dev20220204191113 on 2023-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0013_alter_searchentry_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='file',
            field=models.FileField(blank=True, upload_to='static'),
        ),
    ]
