# Generated by Django 4.1.dev20220204191113 on 2023-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0014_alter_searchentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='link',
            field=models.CharField(default='empty', max_length=1000),
        ),
    ]
