# Generated by Django 4.1.dev20220204191113 on 2023-01-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0017_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
