# Generated by Django 4.1 on 2023-02-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0018_rename_name_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000000)),
                ('explanation', models.CharField(max_length=10000)),
                ('notebook', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('tag', models.CharField(default='', max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='static')),
            ],
        ),
    ]
