# Generated by Django 4.1.dev20220204191113 on 2023-02-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0018_rename_name_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchentry',
            name='name',
            field=models.CharField(max_length=990),
        ),
    ]
