# Generated by Django 4.1 on 2023-02-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0019_codeblockentry_notebookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='file_name',
            field=models.CharField(default='def', max_length=1000),
        ),
    ]
