# Generated by Django 4.1.dev20220204191113 on 2023-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifsearchdemo', '0019_alter_searchentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
